--liquibase formatted sql

--changeset liquibase:4
CREATE TABLE IF NOT EXISTS comment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(255),
    users_id bigint,
    FOREIGN KEY (users_id)
      REFERENCES users(id)
);